version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "twitter-sentiment-lambda-function"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cqzryr3nj5cu"
s3_prefix = "twitter-sentiment-lambda-function"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["twitterSentimentFunction=211862813211.dkr.ecr.eu-north-1.amazonaws.com/twitter-sentiment-lambda-function"]
