/// updateActivePortfoliosConstants ////
export const PORTFOLIO_UPDATE_ACTIVE_REQUEST = "PORTFOLIO_UPDATE_ACTIVE_REQUEST"; 
export const PORTFOLIO_UPDATE_ACTIVE_SUCCESS = "PORTFOLIO_UPDATE_ACTIVE_SUCCESS";
export const PORTFOLIO_UPDATE_ACTIVE_FAIL    = "PORTFOLIO_UPDATE_ACTIVE_FAIL"; 